- action:
  - data:
      message: The sauna is ready for use :) The temp is now {{ states.sensor.sauna.state
        | round(1)  }} °C
      title: Sauna ready ({{ states.sensor.sauna.state | round(1)  }} °C)
    service: notify.push_message
  alias: Sauna ready
  condition: []
  id: '1510330573942'
  trigger:
  - above: '55'
    entity_id: sensor.sauna
    platform: numeric_state
- id: '1510575361424'
  alias: External Lights on
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.rfx_GarageExtLights
    service: homeassistant.turn_on
- id: '1510575855987'
  alias: External Lights off
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.rfx_GarageExtLights
    service: homeassistant.turn_off
- id: '1510576457365'
  alias: Livingroom lights off with tv
  trigger:
  - entity_id: media_player.samsung_led60_ue60f6300
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '21:00'
    condition: time
  action:
  - data:
      entity_id: switch.rfx_new1
    service: homeassistant.turn_off
  - data:
      entity_id: switch.rfx_new2
    service: homeassistant.turn_off
  - data:
      entity_id: switch.rfx_new3
    service: homeassistant.turn_off
- action:
  - data:
      mac: 4C:E6:76:6D:53:81
    service: wake_on_lan.send_magic_packet
  alias: NAS
  condition:
  - condition: state
    entity_id: input_boolean.nas_wol
    state: 'on'
  id: '1511554586438'
  trigger:
    platform: time
    minutes: /1
    seconds: /30
- id: '1518799968022'
  alias: Childrens cameras off
  trigger:
  - at: '9:00'
    platform: time
  - at: '16:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch
    service: homeassistant.turn_off
  - data:
      entity_id: switch.rfx_new6
    service: homeassistant.turn_off
- id: '1518800302919'
  alias: Childrens cameras on
  trigger:
  - at: '20:00'
    platform: time
  - at: '12:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.rfx_new6
    service: homeassistant.turn_on
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch
    service: homeassistant.turn_on
- action:
  - data:
      data:
        sound: siren
      message: Garage getting too cold! The temp is now {{ states.sensor.garage.state
        | round(2)  }} °C
      title: Garage getting too cold! ( {{ states.sensor.garage.state | round(1)  }}
        °C)
    service: notify.push_message
  alias: Garage temp varning
  condition: []
  id: '1519565910987'
  trigger:
  - below: '5'
    entity_id: sensor.garage
    platform: numeric_state
- action:
  - data:
      data:
        sound: none
      message: Garage temp is ok. The temp is now {{ states.sensor.garage.state |
        round(1)  }} °C
      title: Garage temp OK! ( {{ states.sensor.garage.state | round(1)  }} °C)
    service: notify.push_message
  alias: Garage temp ok
  condition: []
  id: '1519567080702'
  trigger:
  - above: '7'
    entity_id: sensor.garage
    platform: numeric_state
- id: '1535654356509'
  alias: Office Pc ON via Dummy switch
  trigger:
  - entity_id: switch.rfx_new4
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.rfx_old1
    service: switch.turn_on
- id: '1535654827705'
  alias: Office Pc OFF via Dummy switch
  trigger:
  - entity_id: switch.rfx_new4
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.rfx_old1
    service: switch.turn_off
