homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  #Customize device names et.c
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

wake_on_lan:

# Enables configuration UI
config:

mqtt:
  broker: 10.0.0.201
  protocol: 3.1
  username: !secret mqttuser
  password: !secret mqttpass



http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

influxdb:
  host: !secret influx_host
#  port: !secret influx_port
  username: !secret influx_username
  password: !secret influx_password
#  ssl: true
#  verify_ssl: false

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Ring.com
ring:
  username: !secret ring_user
  password: !secret ring_password

camera:
  - platform: ring

ffmpeg:

notify:
  - name: Push message
    platform: pushover
    api_key: !secret pushover_apikey
    user_key: !secret pushover_userkey

media_player:
  - platform: denonavr

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

history_graph:
  gr1:
    name: SaunaSensors
    entities:
      - sensor.sauna
      - sensor.saunarh
    hours_to_show: 120

  gr2:
    name: Garage
    entities:
      - sensor.outdoor
      - sensor.garage
      - sensor.garagerh
      - sensor.fibaropowerstats_mean
      - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
    hours_to_show: 120

# View all events in a logbook
logbook:

input_boolean:
  nas_wol:
    name: Buffalo_duo
    initial: off
    icon: mdi:server-network

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr

  - platform: statistics
    name: FibaroPowerStats
    entity_id: sensor.fibaro_system_fgwpef_wall_plug_gen5_power

  - platform: ring
    monitored_conditions:
     - battery
#     - last_activity
     - last_ding
     - last_motion
#     - volume

  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: mqtt
    state_topic: "sensor/sht30/temperature"
    name: "SHT30"
    unit_of_measurement: "°C"
    expire_after: 3600

  - platform: mqtt
    state_topic: "sensor/sht30/humidity"
    name: "SHT30Rh"
    unit_of_measurement: "%RH"
    expire_after: 3600

#command line
  - platform: command_line
#   command: "owread 28.2F5699030000/temperature"
    command: /opt/bash-scripts/owfs_GenericRead.sh 1300000399562F28 Temperature
    name: Noomis
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    #command: "owread 28.4A4699030000/temperature"
    command: /opt/bash-scripts/owfs_GenericRead.sh 4700000399464A28 Temperature
    name: MasterBed
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    #command: "owread 28.CD0BAE030000/temperature"
    #command: "curl  http://10.0.0.202/details.xml --silent | grep E3000003AE0BCD28 -C 5  | grep '<Temperature Units' | cut -d'>' -f 2 | cut -d'<' -f1"
    #command: curl  http://10.0.0.202/details.xml --silent | sed '2 s/xmlns=".*"//g' | xmllint --xpath "string(/Devices-Detail-Response/owd_DS18B20[ROMId='E3000003AE0BCD28']/Temperature)" -
    #command: /opt/bash-scripts/owfs_outsideTemp.sh
    command: /opt/bash-scripts/owfs_GenericRead.sh E3000003AE0BCD28 Temperature
    name: Outdoor
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
  # command: "owread 28.326183050000/temperature"
    command: /opt/bash-scripts/owfs_GenericRead.sh 2500000583613228 Temperature
    name: CTC
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
  # command: "owread 26.35283F010000/temperature"
    command: /opt/bash-scripts/owfs_GenericRead.sh D80000013F283526 Temperature
    name: Sauna
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
#    command: "owread 26.35283F010000/humidity"
    command: /opt/bash-scripts/owfs_GenericRead.sh D80000013F283526 Humidity
    name: SaunaRh
    unit_of_measurement: "%RH"
    scan_interval: 360

  - platform: command_line
   #command: "owread 26.B4423F010000/temperature"
    command: /opt/bash-scripts/owfs_GenericRead.sh A90000013F42B426 Temperature
    name: Garage
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    #command: "owread 26.B4423F010000/humidity"
    command: /opt/bash-scripts/owfs_GenericRead.sh A90000013F42B426 Humidity
    name: GarageRh
    unit_of_measurement: "%RH"
    scan_interval: 360

  - platform: command_line
    command: /opt/bash-scripts/owfs_GenericRead.sh C60000042FF89728 Temperature
    name: Solar
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    command: /opt/bash-scripts/owfs_GenericRead.sh 5800000399382428 Temperature
    name: Office
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    command: /opt/bash-scripts/owfs_GenericRead.sh CC000003C22BA428 Temperature
    name: Foundation
    unit_of_measurement: "°C"
    scan_interval: 360

  - platform: command_line
    #command: echo "scale=2;$(owread 1D.FB970F000000/counters.B) / 53000" | bc
    command: echo "scale=2;$(/opt/bash-scripts/owfs_GenericRead.sh 350000000F97FB1D counters.b) / 53000" | bc
    name: Water
    unit_of_measurement: "m3"
    scan_interval: 360

  - platform: command_line
    command: /opt/bash-scripts/owread_water_cons_liter.sh
    name: WaterCons
    unit_of_measurement: "L"
    scan_interval: 360

  - platform: command_line
    command: echo "scale=2;$(cat /sys/class/thermal/thermal_zone0/temp) / 1000"  | bc
    name: CPU-temp
    unit_of_measurement: "°C"
    scan_interval: 900

#echo "scale=2;$(cat /sys/class/thermal/thermal_zone0/temp) / 1000"  | bc

# Text to speech
tts:
  platform: google

# Example configuration.yaml entry
tellstick:

zwave:
  usb_path: /dev/ttyACM0
# Example configuration.yaml entry

switch:
  - platform: tellstick

group: !include groups.yaml

# Example configuration.yaml entry for nmap
# One whole subnet, and skipping two specific IPs.
device_tracker:
  - platform: nmap_tracker
    hosts: 10.0.0.0/24
    home_interval: 10
    exclude:
     - 10.0.0.66

automation: !include automations.yaml
#automation: !include_dir_list automation/

# Grafana in Home Assistant
#panel_iframe:
#  grafana:
#    title: 'Statistik'
#    icon: mdi:elevation-rise
#    url: !secret grafana_url
